### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by moriarty** [LoyVanBeek/vizbox#3]
Docker image, not because it makes development from a MacBook easier...

But because it makes support easier, and the dockerfile provides reasonable installation instructions.

I can get around to this

**Comment by LoyVanBeek** [comment]
To run the docker image:

```bash
roscore
docker run --net="host" loy1/robocupathome-vizbox
```
Open [the page](http://localhost:8888)
and publish some text:

```bash
rostopic pub /operator_text std_msgs/String "data: 'hello robot'" --once
rostopic pub /robot_text std_msgs/String "data: 'hello fellow human'" --once
rostopic pub /operator_text std_msgs/String "data: 'bye bye robot'" --once
```

and see the text show up at the bottom of the page
